x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  eotsd:
    build:
      context: ./eotsd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: eotsd:local
    pull_policy: never
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - MONIKER=${MONIKER}
      - EXTRA_FLAGS=${EOTSD_EXTRA_FLAGS}
    ports:
      - ${EOTSD_PORT}:${EOTSD_PORT}
    volumes:
      - eotsd-data:/data:rw
    entrypoint:
      - docker-entrypoint.sh
      - eotsd
      - start
      - --rpc-listener
      - 0.0.0.0:${EOTSD_PORT}
      - --home
      - /data/eotsd
    command:
      - start
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=2113
      - metrics.instance=eotsd
      - metrics.network=${NETWORK}

  eotsd-import-keys:
    profiles: ["tools"]
    build:
      context: ./eotsd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
        - USER=finality-provider
    image: eotsd:local
    pull_policy: never
    user: finality-provider
    volumes:
      - eotsd-data:/data:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        eotsd keys add $MONIKER --recover --keyring-backend test

  eotsd-cli:
    profiles: ["tools"]
    build:
      context: ./eotsd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
        - USER=finality-provider
    image: eotsd:local
    pull_policy: never
    user: finality-provider
    volumes:
      - eotsd-data:/data:rw

volumes:
  eotsd-data:
