x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  eotsd:
    build:
      context: ./eotsd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: eotsd:local
    pull_policy: never
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - MONIKER=${MONIKER}
      - EXTRA_FLAGS=${EOTSD_EXTRA_FLAGS}
    ports:
      - ${EOTSD_PORT}:${EOTSD_PORT}
    volumes:
      - eotsd-data:/data:rw
    entrypoint:
      - docker-entrypoint.sh
      - eotsd
      - start
      - --rpc-listener
      - 0.0.0.0:${EOTSD_PORT}
      - --home
      - /data/eotsd
    command:
      - start
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=2113
      - metrics.instance=eotsd
      - metrics.network=${NETWORK}

  eotsd-list-keys:
    profiles: ["tools"]
    build:
      context: ./eotsd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: eotsd:local
    pull_policy: never
    user: eotsd
    volumes:
      - eotsd-data:/data:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        eotsd keys list --keyring-backend test --home /data/eotsd

  eotsd-create-keys:
    profiles: ["tools"]
    build:
      context: ./eotsd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: eotsd:local
    pull_policy: never
    user: eotsd
    volumes:
      - eotsd-data:/data:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        eotsd keys add eotsd --keyring-backend test --home /data/eotsd

  eotsd-import-keys:
    profiles: ["tools"]
    build:
      context: ./eotsd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: eotsd:local
    pull_policy: never
    user: eotsd
    volumes:
      - eotsd-data:/data:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        eotsd keys add eotsd --recover --keyring-backend test --home /data/eotsd

  eotsd-cli:
    profiles: ["tools"]
    build:
      context: ./eotsd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: eotsd:local
    pull_policy: never
    user: eotsd
    volumes:
      - eotsd-data:/data:rw

  eotsd-import-db:
    profiles: ["tools"]
    build:
      context: ./eotsd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: eotsd:local
    pull_policy: never
    user: root
    volumes:
      - eotsd-data:/data:rw
      - ./backup:/backup:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        cp /backup/eots.db /data/eotsd/data/eots.db
        chown eotsd:eotsd /data/eotsd/data/eots.db

  eotsd-export-db:
    profiles: ["tools"]
    build:
      context: ./eotsd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: eotsd:local
    pull_policy: never
    user: root
    volumes:
      - eotsd-data:/data:rw
      - ./backup:/backup:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        cp /data/eotsd/data/eots.db /backup/eots.db

volumes:
  eotsd-data:
