x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  fpd:
    build:
      context: ./fpd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: fpd:local
    pull_policy: never
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - MONIKER=${MONIKER}
      - EXTRA_FLAGS=${FPD_EXTRA_FLAGS}
      - EOTSD_PUBLIC_KEY=${EOTSD_PUBLIC_KEY}
      - EOTSD_PORT=${EOTSD_PORT}
      - RPC_HOST=${RPC_HOST}
      - CL_RPC_PORT=${CL_RPC_PORT}
      - NETWORK=${NETWORK}
      - BABYLOND_HOST=${BABYLOND_HOST}
    ports:
      - ${FPD_PORT}:${FPD_PORT}
    volumes:
      - fpd-data:/data:rw
    entrypoint:
      - docker-entrypoint.sh
      - fpd
      - start
      - --rpc-listener
      - 0.0.0.0:${FPD_PORT}
      - --eots-pk
      - ${EOTSD_PUBLIC_KEY}
      - --home
      - /data/fpd
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=2112
      - metrics.instance=fpd
      - metrics.network=${NETWORK}

  fpd-list-keys:
    profiles: ["tools"]
    build:
      context: ./fpd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: fpd:local
    pull_policy: never
    user: fpd
    volumes:
      - fpd-data:/data:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        fpd keys list --home /data/fpd

  fpd-create-keys:
    profiles: ["tools"]
    build:
      context: ./fpd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: fpd:local
    pull_policy: never
    user: fpd
    volumes:
      - fpd-data:/data:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        fpd keys add finality-provider --home /data/fpd

  fpd-import-keys:
    profiles: ["tools"]
    build:
      context: ./fpd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: fpd:local
    pull_policy: never
    user: fpd
    volumes:
      - fpd-data:/data:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        fpd keys add finality-provider --recover --home /data/fpd

  fpd-cli:
    profiles: ["tools"]
    build:
      context: ./fpd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: fpd:local
    pull_policy: never
    user: fpd
    volumes:
      - fpd-data:/data:rw

  fpd-import-db:
    profiles: ["tools"]
    build:
      context: ./fpd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: fpd:local
    pull_policy: never
    user: root
    volumes:
      - fpd-data:/data:rw
      - ./backup:/backup:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        cp /backup/finality-provider.db /data/fpd/data/finality-provider.db
        chown fpd:fpd /data/fpd/data/finality-provider.db

  fpd-export-db:
    profiles: ["tools"]
    build:
      context: ./fpd
      dockerfile: Dockerfile.binary
      args:
        - FINALITY_PROVIDER_VERSION=${FINALITY_PROVIDER_VERSION}
    image: fpd:local
    pull_policy: never
    user: root
    volumes:
      - fpd-data:/data:rw
      - ./backup:/backup:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        cp /data/fpd/data/finality-provider.db /backup/finality-provider.db

volumes:
  fpd-data:
